### ISSUE TITLE
IOS XCode, Build failed

### ISSUE THREAD

**Issue by kaishuai007** [mopub/mopub-unity-sdk#169]
One line summary of the issue here

- [ ] I am submitting a bug report for existing functionality
- [ ] I visited https://developers.mopub.com/ and found no answer
- [ ] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ ] I checked to make sure that this issue has not already been filed

#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.

#### Expected behavior:
As concisely as possible, describe the expected behavior.

#### Observed behavior:
As concisely as possible, describe the observed behavior.

#### Evidence:
Device log files, Network log file, etc.
mopub-sdk-plugin
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/MoPub-SDK-Plugin-umbrella.h"
        ^
/Users/pksiubad/Documents/ProjectCompany/ExportN/IOSMINIGAME/Pods/Target Support Files/MoPub-SDK-Plugin/MoPub-SDK-Plugin-umbrella.h:13:9: note: in file included from /Users/pksiubad/Documents/ProjectCompany/ExportN/IOSMINIGAME/Pods/Target Support Files/MoPub-SDK-Plugin/MoPub-SDK-Plugin-umbrella.h:13:
#import "MoPubManager.h"
        ^
/Users/pksiubad/Documents/ProjectCompany/3kill/Assets/MoPub/Plugins/iOS/MoPubManager.h:15:9: error: 'MoPub.h' file not found
#import "MoPub.h"
        ^
<unknown>:0: error: could not build Objective-C module 'MoPub_SDK_Plugin'
-------------------------
mopub-ios-sdk
Command CompileSwift failed with a nonzero exit code

**Comment by BlueSpiritbox** [comment]
I have the same issue after updating the MoPub SDK to 5.16.1. **'MoPub.h' file not found.** I'm using Unity 2019.4.17f with:
-  AdMob Mediation SDK
- Facebook Audience Network Mediation SDK
- UnityAds Mediation SDK
- Google Firebase Analytics & Crashlytics

**Comment by dravyan** [comment]
Hi, thank you for the report. We will take a look and get back to you once we have an update to share.

Thanks,
MoPub Team

**Comment by kaishuai007** [comment]
> Hi, thank you for the report. We will take a look and get back to you once we have an update to share.
> 
> Thanks,
> MoPub Team

Thanks，please reply as soon as possible

**Comment by dravyan** [comment]
@kaishuai007 , let us know if the [workaround suggested](https://github.com/mopub/mopub-unity-sdk/issues/161#issuecomment-754582212) in the other report resolves the issue? Thanks.

**Comment by BlueSpiritbox** [comment]
@dravyan I tried the workaround, but it didn't work for me unfortunately. Still getting the same error.

**Comment by tfeyow** [comment]
I have the same issue. 
Unity 2020.2.5f1c1

**Comment by kaishuai007** [comment]
> @kaishuai007 , let us know if the [workaround suggested](https://github.com/mopub/mopub-unity-sdk/issues/161#issuecomment-754582212) in the other report resolves the issue? Thanks.

not resolves，gett the same error。the old version can be work, I think maybe it's caused by the addition of swift.

**Comment by kaishuai007** [comment]
> @kaishuai007 , let us know if the [workaround suggested](https://github.com/mopub/mopub-unity-sdk/issues/161#issuecomment-754582212) in the other report resolves the issue? Thanks.

only build 'MoPub_SDK_Plugin' error :
------------------
CompileSwift normal arm64 /Users/pksiubad/Documents/ProjectMy/MopubProj/Assets/MoPub/Plugins/iOS/SwiftCompatibility.swift (in target 'MoPub-SDK-Plugin' from project 'Pods')
    cd /Users/pksiubad/Documents/ProjectMy/ExportIos/Pods
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -c -primary-file /Users/pksiubad/Documents/ProjectMy/MopubProj/Assets/MoPub/Plugins/iOS/SwiftCompatibility.swift -emit-module-path /Users/pksiubad/Library/Developer/Xcode/DerivedData/Unity-iPhone-bbwpuzzykyoabwcyuhlosehcrcml/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/MoPub-SDK-Plugin.build/Objects-normal/arm64/SwiftCompatibility\~partial.swiftmodule -emit-module-doc-path /Users/pksiubad/Library/Developer/Xcode/DerivedData/Unity-iPhone-bbwpuzzykyoabwcyuhlosehcrcml/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/MoPub-SDK-Plugin.build/Objects-normal/arm64/SwiftCompatibility\~partial.swiftdoc -emit-module-source-info-path /Users/pksiubad/Library/Developer/Xcode/DerivedData/Unity-iPhone-bbwpuzzykyoabwcyuhlosehcrcml/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/MoPub-SDK-Plugin.build/Objects-normal/arm64/SwiftCompatibility\~partial.swiftsourceinfo -serialize-diagnostics-path /Users/pksiubad/Library/Developer/Xcode/DerivedData/Unity-iPhone-bbwpuzzykyoabwcyuhlosehcrcml/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/MoPub-SDK-Plugin.build/Objects-normal/arm64/SwiftCompatibility.dia -emit-dependencies-path /Users/pksiubad/Library/Developer/Xcode/DerivedData/Unity-iPhone-bbwpuzzykyoabwcyuhlosehcrcml/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/MoPub-SDK-Plugin.build/Objects-normal/arm64/SwiftCompatibility.d -emit-reference-dependencies-path /Users/pksiubad/Library/Developer/Xcode/DerivedData/Unity-iPhone-bbwpuzzykyoabwcyuhlosehcrcml/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/MoPub-SDK-Plugin.build/Objects-normal/arm64/SwiftCompatibility.swiftdeps -target arm64-apple-ios9.0 -Xllvm -aarch64-use-tbi -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.4.sdk -I /Users/pksiubad/Library/Developer/Xcode/DerivedData/Unity-iPhone-bbwpuzzykyoabwcyuhlosehcrcml/Build/Products/Debug-iphoneos/MoPub-SDK-Plugin -F /Users/pksiubad/Library/Developer/Xcode/DerivedData/Unity-iPhone-bbwpuzzykyoabwcyuhlosehcrcml/Build/Products/Debug-iphoneos/MoPub-SDK-Plugin -enable-testing -g -import-underlying-module -module-cache-path /Users/pksiubad/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -swift-version 5 -enforce-exclusivity\=checked -Onone -D DEBUG -D COCOAPODS -serialize-debugging-options -Xcc -working-directory -Xcc /Users/pksiubad/Documents/ProjectMy/ExportIos/Pods -enable-anonymous-context-mangled-names -Xcc -I/Users/pksiubad/Library/Developer/Xcode/DerivedData/Unity-iPhone-bbwpuzzykyoabwcyuhlosehcrcml/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/MoPub-SDK-Plugin.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/pksiubad/Library/Developer/Xcode/DerivedData/Unity-iPhone-bbwpuzzykyoabwcyuhlosehcrcml/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/MoPub-SDK-Plugin.build/MoPub_SDK_Plugin-generated-files.hmap -Xcc -I/Users/pksiubad/Library/Developer/Xcode/DerivedData/Unity-iPhone-bbwpuzzykyoabwcyuhlosehcrcml/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/MoPub-SDK-Plugin.build/MoPub_SDK_Plugin-own-target-headers.hmap -Xcc -I/Users/pksiubad/Library/Developer/Xcode/DerivedData/Unity-iPhone-bbwpuzzykyoabwcyuhlosehcrcml/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/MoPub-SDK-Plugin.build/MoPub_SDK_Plugin-all-non-framework-target-headers.hmap -Xcc -ivfsoverlay -Xcc /Users/pksiubad/Library/Developer/Xcode/DerivedData/Unity-iPhone-bbwpuzzykyoabwcyuhlosehcrcml/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/MoPub-SDK-Plugin.build/all-product-headers.yaml -Xcc -iquote -Xcc /Users/pksiubad/Library/Developer/Xcode/DerivedData/Unity-iPhone-bbwpuzzykyoabwcyuhlosehcrcml/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/MoPub-SDK-Plugin.build/MoPub_SDK_Plugin-project-headers.hmap -Xcc -I/Users/pksiubad/Library/Developer/Xcode/DerivedData/Unity-iPhone-bbwpuzzykyoabwcyuhlosehcrcml/Build/Products/Debug-iphoneos/MoPub-SDK-Plugin/include -Xcc -I/Users/pksiubad/Library/Developer/Xcode/DerivedData/Unity-iPhone-bbwpuzzykyoabwcyuhlosehcrcml/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/MoPub-SDK-Plugin.build/DerivedSources-normal/arm64 -Xcc -I/Users/pksiubad/Library/Developer/Xcode/DerivedData/Unity-iPhone-bbwpuzzykyoabwcyuhlosehcrcml/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/MoPub-SDK-Plugin.build/DerivedSources/arm64 -Xcc -I/Users/pksiubad/Library/Developer/Xcode/DerivedData/Unity-iPhone-bbwpuzzykyoabwcyuhlosehcrcml/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/MoPub-SDK-Plugin.build/DerivedSources -Xcc -DPOD_CONFIGURATION_DEBUG\=1 -Xcc -DDEBUG\=1 -Xcc -DCOCOAPODS\=1 -Xcc -ivfsoverlay -Xcc /Users/pksiubad/Library/Developer/Xcode/DerivedData/Unity-iPhone-bbwpuzzykyoabwcyuhlosehcrcml/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/MoPub-SDK-Plugin.build/unextended-module-overlay.yaml -target-sdk-version 14.4 -parse-as-library -module-name MoPub_SDK_Plugin -o /Users/pksiubad/Library/Developer/Xcode/DerivedData/Unity-iPhone-bbwpuzzykyoabwcyuhlosehcrcml/Build/Intermediates.noindex/Pods.build/Debug-iphoneos/MoPub-SDK-Plugin.build/Objects-normal/arm64/SwiftCompatibility.o -embed-bitcode-marker -index-store-path /Users/pksiubad/Library/Developer/Xcode/DerivedData/Unity-iPhone-bbwpuzzykyoabwcyuhlosehcrcml/Index/DataStore -index-system-modules

<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/MoPub-SDK-Plugin-umbrella.h"
        ^
/Users/pksiubad/Documents/ProjectMy/ExportIos/Pods/Target Support Files/MoPub-SDK-Plugin/MoPub-SDK-Plugin-umbrella.h:13:9: note: in file included from /Users/pksiubad/Documents/ProjectMy/ExportIos/Pods/Target Support Files/MoPub-SDK-Plugin/MoPub-SDK-Plugin-umbrella.h:13:
#import "MoPubManager.h"
        ^
/Users/pksiubad/Documents/ProjectMy/MopubProj/Assets/MoPub/Plugins/iOS/MoPubManager.h:15:9: error: include of non-modular header inside framework module 'MoPub_SDK_Plugin.MoPubManager': '/Users/pksiubad/Documents/ProjectMy/ExportIos/Pods/mopub-ios-sdk/MoPubSDK/MoPub.h'
#import "MoPub.h"
        ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/MoPub-SDK-Plugin-umbrella.h"
        ^
/Users/pksiubad/Documents/ProjectMy/ExportIos/Pods/Target Support Files/MoPub-SDK-Plugin/MoPub-SDK-Plugin-umbrella.h:13:9: note: in file included from /Users/pksiubad/Documents/ProjectMy/ExportIos/Pods/Target Support Files/MoPub-SDK-Plugin/MoPub-SDK-Plugin-umbrella.h:13:
#import "MoPubManager.h"
        ^
/Users/pksiubad/Documents/ProjectMy/MopubProj/Assets/MoPub/Plugins/iOS/MoPubManager.h:81:1: warning: declaration does not declare anything
__deprecated_msg("createBanner has been deprecated, please use requestBanner instead.");
^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.4.sdk/usr/include/sys/cdefs.h:200:33: note: expanded from macro '__deprecated_msg'
        #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                       ^
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "Headers/MoPub-SDK-Plugin-umbrella.h"
        ^
/Users/pksiubad/Documents/ProjectMy/ExportIos/Pods/Target Support Files/MoPub-SDK-Plugin/MoPub-SDK-Plugin-umbrella.h:13:9: note: in file included from /Users/pksiubad/Documents/ProjectMy/ExportIos/Pods/Target Support Files/MoPub-SDK-Plugin/MoPub-SDK-Plugin-umbrella.h:13:
#import "MoPubManager.h"
        ^
/Users/pksiubad/Documents/ProjectMy/MopubProj/Assets/MoPub/Plugins/iOS/MoPubManager.h:82:23: warning: 'MoPubBannerType' is deprecated: MoPubBannerType has been deprecated, please use MoPubAdSize instead.
- (void)createBanner:(MoPubBannerType)bannerType atPosition:(MoPubAdPosition)position;
                      ^
/Users/pksiubad/Documents/ProjectMy/MopubProj/Assets/MoPub/Plugins/iOS/MoPubManager.h:18:1: note: 'MoPubBannerType' has been explicitly marked deprecated here
__deprecated_enum_msg("MoPubBannerType has been deprecated, please use MoPubAdSize instead.")
^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.4.sdk/usr/include/sys/cdefs.h:206:38: note: expanded from macro '__deprecated_enum_msg'
        #define __deprecated_enum_msg(_msg) __deprecated_msg(_msg)
                                            ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS14.4.sdk/usr/include/sys/cdefs.h:200:48: note: expanded from macro '__deprecated_msg'
        #define __deprecated_msg(_msg) __attribute__((__deprecated__(_msg)))
                                                      ^
<unknown>:0: error: could not build Objective-C module 'MoPub_SDK_Plugin'

**Comment by chyen01** [comment]
Have the same issue with 2020.2.5f1.

'MoPub.h' file not found

**Comment by dravyan** [comment]
@kaishuai007, could you share your project repo for us to investigate further?

**Comment by kaishuai007** [comment]
> @kaishuai007, could you share your project repo for us to investigate further? Another possible workaround is to update the import header in [MoPubManager.h](https://github.com/mopub/mopub-unity-sdk/blob/19bffd3a328c30d3e321f1e93bce3c5f9be1061a/unity-sample-app/Assets/MoPub/Plugins/iOS/MoPubManager.h#L10-L11) as follows;
> 
> ```
> #if __has_include(<MoPubSDK/MoPub.h>)
> #import <MoPubSDK/MoPub.h>
> ```
> 
> and confirm that the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` is set to `YES` in your XCode project. Let us know how it goes.

my test is in empty unity project，import moput sdk

in mopubmanager.h 

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>
#if __has_include(<MoPub/MoPub.h>)
#import <MoPub/MoPub.h>
#elif __has_include(<MoPubSDKFramework/MoPub.h>)
#import <MoPubSDKFramework/MoPub.h>
#else
#import "MoPub.h"    ------ this is the wrong location as follows
#endif

Include of non-modular header inside framework module 'MoPub_SDK_Plugin.MoPubManager': '/Users/pksiubad/Documents/ProjectMy/ExportIos/Pods/mopub-ios-sdk/MoPubSDK/MoPub.h'

**Comment by BlueSpiritbox** [comment]
> @kaishuai007, could you share your project repo for us to investigate further? Another possible workaround is to update the import header in [MoPubManager.h](https://github.com/mopub/mopub-unity-sdk/blob/19bffd3a328c30d3e321f1e93bce3c5f9be1061a/unity-sample-app/Assets/MoPub/Plugins/iOS/MoPubManager.h#L10-L11) as follows;
> 
> ```
> #if __has_include(<MoPubSDK/MoPub.h>)
> #import <MoPubSDK/MoPub.h>
> ```
> 
> and confirm that the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` is set to `YES` in your XCode project. Let us know how it goes.

Tested this as well. Didn't work for me either. The error is still raised at "#import "MoPub.h" - MoPub.h file not found"

**Comment by agrobost** [comment]
Same here again...

**Comment by kaishuai007** [comment]
> @kaishuai007, could you share your project repo for us to investigate further? Another possible workaround is to update the import header in [MoPubManager.h](https://github.com/mopub/mopub-unity-sdk/blob/19bffd3a328c30d3e321f1e93bce3c5f9be1061a/unity-sample-app/Assets/MoPub/Plugins/iOS/MoPubManager.h#L10-L11) as follows;
> 
> ```
> #if __has_include(<MoPubSDK/MoPub.h>)
> #import <MoPubSDK/MoPub.h>
> ```
> 
> and confirm that the `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` is set to `YES` in your XCode project. Let us know how it goes.

I found that they were all static libraries before, but now they are dynamic libraries. Is that the reason?

**Comment by pixeption** [comment]
This workaround works for me with an additional step
https://github.com/mopub/mopub-unity-sdk/issues/151#issue-747782146.

Workaround:
- Remove <iosPod name="MoPub-SDK-Plugin" minTargetSdk="10.0" path="Assets/MoPub/Plugins/iOS"/> from MoPubDependencies.xml
- Delete Assets/MoPub/Plugins/iOS/MoPub-SDK-Plugin.podspec
- Check iOS as platform for plugin for all files inside Assets/MoPub/Plugins/iOS
- Enable Objective-C Exceptions: Yes

**Comment by kaishuai007** [comment]
> This workaround works for me with an additional step
> [#151 (comment)](https://github.com/mopub/mopub-unity-sdk/issues/151#issue-747782146).
> 
> Workaround:
> 
> * Remove `<iosPod name="MoPub-SDK-Plugin" minTargetSdk="10.0" path="Assets/MoPub/Plugins/iOS"/>` from MoPubDependencies.xml
> * Delete Assets/MoPub/Plugins/iOS/MoPub-SDK-Plugin.podspec
> * Check iOS as platform for plugin for all files inside Assets/MoPub/Plugins/iOS
> * Enable Objective-C Exceptions: Yes

thanks, it works for me.

**Comment by zenith-jacob** [comment]
Doesn't work for us (Unity 2020.2.1f1)
Mopub 5.16.1

Even with the Objective-C Exceptions workaround above.
In earlier versions the above steps worked (without Objective C Exceptions).

From now on (5.16.1) - they don't work anymore.

**Comment by BlueSpiritbox** [comment]
> Doesn't work for us (Unity 2020.2.1f1)
> Mopub 5.16.1
> 
> Even with the Objective-C Exceptions workaround above.
> In earlier versions the above steps worked (without Objective C Exceptions).
> 
> From now on (5.16.1) - they don't work anymore.

I managed to get it to build by enabling Objective-C Exceptions in the Project - Build Settings. Enabling Objective-C Exceptions in Target or Pods - Build Settings didn't work for me. I had to make sure it was enabled in the Project - Build Settings in Xcode.
